# Generated by Django 3.2.15 on 2022-08-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateField()),
                ('base', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
